function tv = d4_present(tmpstr)

clearvars checkerPass
for i = 1:length(tmpstr)
    if contains(tmpstr(i),"byr")...
            && contains(tmpstr(i),"iyr")...
            && contains(tmpstr(i),"eyr")...
            && contains(tmpstr(i),"hgt")...
            && contains(tmpstr(i),"hcl")...
            && contains(tmpstr(i),"pid")...
            && contains(tmpstr(i),"ecl")
        checkerPass(i) = 1;
    end
end
tv = tmpstr(logical(checkerPass));

end